version: '3.8'
services:
  java-maven-app:
    image: samiselim/java-maven-app-image:1.0.3
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd
