apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-deployment
  labels: 
    app: $APP_NAME
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
          - name: secret-reg
      containers:
      - name: $APP_NAME-container
        image: samiselim/java-maven-app-image:1.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
