apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-deployment
  labels: 
    app: $APP_NAME
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
          - name: my-key
      containers:
      - name: $APP_NAME-container
        image: $DOCKER_REPO/$IMAGE_NAME:$IMAGE_VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
